---
- name: Ensure that the osticket package is installed
  tags: osticket
  become: true
  yum:
    enablerepo: "linuxhq-{{ linuxhq_pkg }}"
    name: osticket
    state: present
  register: osticket_yum

- name: Attempting to overlay incoming email alias
  tags: osticket
  become: true
  lineinfile:
    dest: /etc/aliases
    line: "{{ osticket_pipe }}:\t\t|{{ osticket_documentroot }}/api/pipe.php"
    state: present
  notify: newaliases
  when: osticket_yum is success

- name: Attempting to overlay osticket configurations
  tags: osticket
  become: true
  template:
    src: osticket.conf.j2
    dest: /etc/httpd/conf.d/osticket.conf
    owner: root
    group: root
    mode: 0644
  when: osticket_yum is success
...
